allowed:
  origins:
    https://engangsstonad.nav.no,
    https://foreldrepenger.nav.no,
    https://foreldrepengesoknad.nav.no,
    https://svangerskapspengesoknad.nav.no,
    https://www.nav.no

mellomlagring:
  tmp:
    navn: mellomlagring-prod

virus:
  uri: http://clamav.nais-system/scan

no.nav:
  security:
    jwt:
      client:
        registration:
          fpsoknad-mottak:
            token-exchange:
              audience: prod-fss:teamforeldrepenger:fpsoknad-mottak
          fpoversikt:
            token-exchange:
              audience: prod-gcp:teamforeldrepenger:fpoversikt
oppslag:
  uri: http://fpoversikt
mottak:
  uri: https://fpsoknad-mottak.prod-fss-pub.nais.io/api/
pdfgenerator:
  uri: http://fpdokgen
oversikt:
  uri: http://fpoversikt
