no.nav:
  security:
    jwt:
      dont-propagate-bearertoken: false
      client:
        registration:
          fpsoknad-mottak:
            well-known-url: ${token.x.well.known.url}
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            authentication:
              client-id: ${token.x.client.id}
              client-jwk: ${token.x.private.jwk}
              client-auth-method: private_key_jwt
          fpoversikt:
            well-known-url: ${token.x.well.known.url}
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            authentication:
              client-id: ${token.x.client.id}
              client-jwk: ${token.x.private.jwk}
              client-auth-method: private_key_jwt
      issuer:
        tokenx:
          discovery-url: ${token.x.well.known.url}
          accepted-audience: ${token.x.client.id}
virus:
  enabled: true

management:
  health:
    refresh:
      enabled: false
    diskspace:
      enabled: false
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: /internal/actuator
server:
  servlet:
    context-path: /
  forward-headers-strategy: native
  shutdown: graceful
spring:
  cloud.discovery.enabled: false
  application:
    name: foreldrepengesoknad-api
  main:
    banner-mode: 'off'
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    throw-exception-if-no-handler-found: true
springdoc:
  packages-to-scan: no.nav.foreldrepenger.selvbetjening
  swagger-ui:
    disable-swagger-default-url: true
