FROM navikt/java:14
COPY target/*.jar "/app/app.jar"
ENV APPD_ENABLED=true
ENV APP_NAME=foreldrepengesoknad-api
ENV APPDYNAMICS_CONTROLLER_HOST_NAME=appdynamics.adeo.no
ENV APPDYNAMICS_CONTROLLER_PORT=443
ENV APPDYNAMICS_CONTROLLER_SSL_ENABLED=true
