allowed:
  origins:
    https://svangerskapspengesoknad.dev.nav.no,
    https://engangsstonad.dev.nav.no,
    https://foreldrepengeplanlegger.dev.nav.no,
    https://foreldrepengesoknad.dev.nav.no,
    https://foreldrepengesoknad-rework.dev.nav.no,
    https://foreldrepenger.dev.nav.no,
    https://foreldrepengesoknad.ekstern.dev.nav.no

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  mvc:
    log-request-details: true
  cloud:
    vault:
      enabled: false
virus:
  uri: http://clamav.clamav/scan

no.nav:
  security:
    jwt:
      client:
        registration:
          fpsoknad-mottak:
            token-exchange:
              audience: dev-fss:teamforeldrepenger:fpsoknad-mottak
          fpinfo-historikk:
            token-exchange:
              audience: dev-fss:teamforeldrepenger:fpinfo-historikk

oppslag:
  uri: https://fpsoknad-mottak.dev-fss-pub.nais.io/api/
historikk:
  uri: https://fpinfo-historikk.dev-fss-pub.nais.io/api/
mottak:
  uri: https://fpsoknad-mottak.dev-fss-pub.nais.io/api/
innsyn:
  uri: https://fpsoknad-mottak.dev-fss-pub.nais.io/api/
minidialog:
  uri: https://fpinfo-historikk.dev-fss-pub.nais.io/api/
fppdfgen:
  uri: http://fppdfgen
