package no.nav.foreldrepenger.selvbetjening.tjeneste.minidialog;

public enum SøknadType {
    INITIELL_FORELDREPENGER, ETTERSENDING_FORELDREPENGER, ENDRING_FORELDREPENGER,
    INITIELL_ENGANGSSTØNAD, ETTERSENDING_ENGANGSSTØNAD,
    INITIELL_ENGANGSSTØNAD_DOKMOT, INITIELL_SVANGERSKAPSPENGER,
    ETTERSENDING_SVANGERSKAPSPENGER, UKJENT;

}
