apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: foreldrepengesoknad-api
  namespace: teamforeldrepenger
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
    config.linkerd.io/proxy-outbound-connect-timeout: "2s"
  labels:
    team: teamforeldrepenger
spec:
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
  envFrom:
    - secret: api-storage
  gcp:
    buckets:
      - name: {{tmpbucket}}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  accessPolicy:
    outbound:
      rules:
        - application: fpdokgen
        - application: fpoversikt
        - application: clamav
          namespace: nais-system
      external:
        {{#each external as |url|}}
        - host: {{url}}
        {{/each}}
  image: {{image}}
  port: 8080
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 80
  liveness:
    path: /internal/actuator/health/liveness
    initialDelay: 15
  readiness:
    path: /internal/actuator/health/readiness
    initialDelay: 15
  preStopHook:
    http:
      path: /internal/preStop
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}
    {{/each}}
  resources:
    limits:
      cpu: "{{limits.cpu}}"
      memory: "{{limits.mem}}"
    requests:
      cpu: "{{requests.cpu}}"
      memory: "{{requests.mem}}"
  secureLogs:
    enabled: true
