apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: foreldrepengesoknad-api
  namespace: teamforeldrepenger
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
  labels:
    team: teamforeldrepenger
spec:
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: {{wonderwall}}
      autoLogin: false
      autoLoginIgnorePaths:
        - /rest/konto
  envFrom:
    {{#if wonderwall}}
    - secret: api-storage
    {{else}}
    - configmap: loginservice-idporten
    - secret: api-storage
    {{/if}}
  gcp:
    buckets:
      - name: {{tmpbucket}}
        lifecycleCondition:
          age: 1
  accessPolicy:
    outbound:
      rules:
        - application: fppdfgen
        - application: fpoversikt
        - application: clamav
          namespace: nais-system
      external:
        {{#each external as |url|}}
        - host: {{url}}
        {{/each}}
  image: {{image}}
  port: 8080
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 80
  liveness:
    path: /internal/actuator/health/liveness
    initialDelay: 15
  readiness:
    path: /internal/actuator/health/readiness
    initialDelay: 15
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}
    {{/each}}
  resources:
    limits:
      cpu: 1500m
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 2560Mi
  secureLogs:
    enabled: true
