apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: foreldrepengesoknad-api
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
{{#if tokenx}}
  tokenx:
    enabled: true
{{/if}}
  envFrom:
     - configmap: loginservice-idporten
{{#if gcp}}
     - secret: apigw
  gcp:
    buckets:
      - name: {{tmpbucket}}
        lifecycleCondition:
          age: 1
  accessPolicy:
     outbound:
       rules:
        - application: clamav
          namespace: clamav
       external:
         - host: storage.googleapis.com
         - host: oauth2.googleapis.com
         - host: www.googleapis.com
{{#if gw}}
         - host: {{gw}}
{{/if}}
{{#each tokenxurl as |url|}}
         - host: {{url}}
{{/each}}
{{/if}}
  image: {{image}}
  port: 8080
  replicas:
      min: 2
      max: 3
  liveness:
      path: /internal/actuator/health/liveness
      initialDelay: 60
  readiness:
      path: /internal/actuator/health/readiness
      initialDelay: 60
  prometheus:
      enabled: true
      path: /internal/actuator/prometheus
  ingresses:
{{#each ingresses as |url|}}
    - {{url}}
{{/each}}
  resources:
      limits:
         cpu: 1500m
         memory: 3072Mi
      requests:
         cpu: 50m
         memory: 1024Mi
{{#unless gcp}}
  webproxy: true
{{/unless}}
