name: Deploy manuelt
on:
  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string
        description: 'Image tag to deploy (example 2023.03.10.080433-f821119)'
      environment:
        required: true
        type: choice
        description: 'The environment to deployed to (dev|prod)'
        options:
          - dev
          - prod

jobs:
  deploy:
    name: Deploy dev
    permissions:
      id-token: write
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      gar: true
      image: ${{ inputs.image }}
      cluster: ${{ inputs.environment }}-gcp
    secrets: inherit
