name: Slash command dispatch
on:
  issue_comment:
    types: [ created ]

jobs:
  dispatcher:
    name: Command
    uses: navikt/fp-gha-workflows/.github/workflows/dispatch.yml@main
    secrets: inherit
